language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: LX+Fx0foihBPjvTLFNFcS+JlvZ/hfLwotCocvLvlPD7LijUwBaV0V/34Dks+yOtZhn0rB6GiAd9C5JDMUZWG6BtECsvb2dkZANfbqxPN8wEpEYTaW193SeoPpwBR1Vdo0J9KXkQQ1VpBGKncu8z3S27i2FSqBwJabHw1fymK7LVsOp6l+j/UBHGMOeEcnwZuYNpdxEzLVngJosy0OGJR4U88J5kp6kJU/5ERcbFJe1n2qe0UhCp2d+kEDA+0fbUeFDbU3yP4nL5ltBRjtvZcA9Cf1MEd+HRV9lYsQknVhB8+IanVOZ7bwz6AAyPFj4Sh8ioh7eaywhGvpVv8D7qtQ2O7aDPMxIA5E3al3Cbo5MX7w1NM9HF3ZWNgrIfHy1CvU8p60K690FOOtu9HvoUVUolRju4+BxdlrsFEUcDBiCvFmlXRY00bwOeVltN4I9VAnXU+SSi0LM1oGX9FWCIOiDGM6oSxcbgfaygCNv1ZRsWo8M4RSECiPZSu9UmWu0UW7+0G+4snyfQEAPoy2HkpRAmZ8UVIZ8zzoe3aCyXN6UhSp2WEFM0bnC4PBlws7ssaoPBb8/dDi5xqHNH70hlo6f98NyTFZ2SQmvhvgUCORiLjEfmYJSYy4NtJVblCgCIOTKjygNlWvhdFA3LWHz+UTmT69L+48Fiqo/9fsIbj114=
  - secure: bQd6Wbt5NZf7dAofIEifE+OqBTROtieLUkjqi2aV9nbZK2RQq2EippTWRhD5pp8bAe7OXL+rsgBJjyYjoM86LQmpPYfC7ao5DLil5oLsik/co0s458uTl2GFnxyUBe32Xhw9N8/pLf+zsFJCokWidwDE4BQ3a68j5gn7PP64qp+xmVYq0Uh3qIiFhKkhAUVsd6TbOuB1iXuMCmCe8KnlD2crSSSyAwHfAmrnDEF3YH+Uk++fWUOkNOqfEO4AwbXvSGMFK0Y7wa5q4fTY9Sj7os4R3se0iMsBLNn7DdM6kd5n6hOpCM3QBFkd6RuvEaCEP5wuZ4P3p3wmHTiXqzHv2uS2m5kx1wWljQ6FAwm0QIUoT1FS9FndPoyl9ZOUHnopAnaaCvAVYCh2ZCDIDA/dLDcBdkU+L5lrC2134GCZs2vuLYRQuEIAltJUEg0rZ+oVykM9JWOe3MjYkvMtnlOyhMIF68bnuPqLcfgtY1aqhsPfJKYgF1cGKy2up1pKykfgA/teOuRj8ODDr/Ad2JuuHG87QmLMiLfK2R65e1WEBpUYRDRgHSsvIvDcekev/6600lRYbgLIAyzAmFIIlVW3EoWlSdwHGLWHRBtr9HNSRjpjmFpAOvEXRj+IUIi4EZV5KUUfq8VtzlX3WjzeG9bvr0Qf4AQsqtbJPk0O1bBZ3v4=
  - secure: e7j3HuFlD0HPTXcE/RukDfG/TC3N8n9yRlBKl5rnOY19cASlGPxFoELbuU0ZjmxTW2sNsCAwYpGb+AprILtbHVsiNC0Ujyh77dYua/neXgL9yD9LOlWj5/kg7hnyCIwWaUWd5Hvs9vZL6HbZbDDUMiQ4rRajLHP1XH6OD384QMZXkshzuo7cu0tifaLWrB5mmeMmYJtgpahdM4jYASma6Tb9K6lmcIqUxW3PFQAhHZtEeT786pn8NYGJpgtQcZbW7Z3CARzUzizKDmSrDoc9BGU270Qw9ZEZjwLAJ2s2CP6c/MSSyPNw2H5cS0BzP/kNDwttRBG4ANgeXY4nKlyEB56Mw3SlZQWQu9J26+z76gLtAcGaJHgOr532NQzCsCXuLzp6huwb6Ioo5JpwKDAJKfojXY80tYw6scDJaN9pUNbRRlGScHn+Twz4YN3nZ69rqj6W/jM1LEkxW5bcJ5dVuHvDVodVwKRA5dN98e5fACnNMPrmARmJsw+6RX5fEeUImZB9A/8NcSBrIAsjU9lZjkoiufsg6bG0Mbp/Ayehl5r0vjY7Ss1+0a34Mr9T3GeLdH33dtV+xWGdN15rMNg83Jq4MmYVG59KM3OPPdNxtbC+20lb4fYwgWpna/CgjzDgA+Kb1kKcm6wLVSahg7Wno80dcxUsQjRsYo3L6AticVo=
  - secure: kIuziF13PVBFJOVHgrZRgw6EHzz2oI5RRKX8Ycc+kU/zht70+oHJDBrUMYIeOkcICQ7/wSA8NaDtxEEEWK1Dl6xJUevyca/dYoQy9Lgx9jDhGumh9+2s4fxFRj62X8oTyYZNpHcbt8a/5ZvmGu418lKybCcRFZrsB/OdHHf38StosI7kT0NYUILPZAxkDkL9HTrJmpUNIUpB+NC1Hf1BahDlqddWBV/xXaK5x16jnY5SFNPkt/0w1EJ76al9Bh9/+gKpIM5nsNidOj+ohTw4Y7bAEbIhe9GrwGRKC9HDZtRo/G8kikNxcs0C6isu0QfZij0jIh6nEKpsgwxUYKlQ1lJEfNiDECADKDjM/B8QzJUpbtGv7rooMAxVjEgI0nr6bQfKyhntk52HnOOh7ajaU4rmXWGA/PKWrFRzixu9C2oxSxn3dOVgIMWzTMT7eHAFn3ubXwwZ78zsgjDETN6weo6jcipn8n2xPhIbIesNVmi9ocpKdOUIagq271zHW5PogkDV5d5vBlZvxKRPAHr3lT9NGhp5w33fy4FZAqCM9aQruF3VCsqJ+jJDd3XYLtijvQ4RsYFs7LeXxpWSjhDuX/hIOG7FIK0u+PedXlPAefyxCQWfrKBHGd4P+9B0hZ7MW7AdynXbzTGyf3UG3c3l0Lg68LPBbPsr6OIvY7UJGA0=

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
  branch:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

before_script:
- ./gradlew clean
- mkdir build build/classes build/classes/test
- cp -r src/test/java/resources build/classes/test/resources

script:
- ./gradlew test && ./gradlew jar

after_success:
- ./gradlew jacocoTestReport coveralls
- .utility/initiate-publish.sh