language: java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
  branch:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

before_script:
- ./gradlew clean
- mkdir build build/classes build/classes/test
- cp -r src/test/java/resources build/classes/test/resources

script:
- ./gradlew test && ./gradlew jar

after_success:
- ./gradlew jacocoTestReport coveralls
- .utility/initiate-publish.sh